### ISSUE TITLE
[NEW] where to list other lists of AI projects in GLAMs?

### ISSUE THREAD

**Issue by mialondon** [AI4LAM/awesome-ai4lam#2]
### Provide a URL for the new item

https://docs.google.com/spreadsheets/d/1A7IVnucQZ0ICxYSOCjqQ1oV3xGgNzDKtIYGrk6smV7w/edit#gid=0

### Describe the new item as concisely as possible

List of Artificial Intelligence (AI) initiatives in museums, compiled in 2021 by Elena Villaespesa, Oonagh Murphy and Kate Nadel for the [Museums+AI Network](https://themuseumsai.network/) project. For each project they note Museum / Research team, Project title, Description, AI technology, Data, Date, Links and references.

### Name the section where the item should be added

Other curated lists of AI projects in libraries, archives and museums

### Issue Checklist

- [X] I have checked that the item does not already exist in the list
- [X] I have provided a concise description of the addition
- [X] I have explained where I think the addition belongs in the awesome list

**Comment by mhucka** [comment]
Thanks for this. It seemed like this fit with the general idea of "projects and case studies", so I renamed that section to "Projects, Initiatives, and Case Studies" and then added this item there.

If you feel strongly that a new section should be created for lists of curated projects, please do write a comment here and reopen the ticket! My rationale is simply that the list still has a lot of empty sections, so it seemed better to try to adjust the sections/clusters to make them fit for the content we want to add, rather than to add more sections. However, I'm conscious that this view is a product of my particular experiences and thought processes, and not necessarily shared by other people. Feedback is welcome!

**Comment by mialondon** [comment]
@mhucka that makes sense to me! I've only really seen the IIIF 'awesome' page in action, so I'm not familiar with how they generally work and change over time. Thanks so much for your very clear explanations.
